package wgu.dansmithc195project.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import java.io.IOException;
import java.net.URL;
import java.time.*;
import java.util.ResourceBundle;
import wgu.dansmithc195project.models.Contact;
import wgu.dansmithc195project.models.Customer;
import wgu.dansmithc195project.models.User;

/**
 * This controller is a form to add appointments to the database. The appointment ID will be autogenerated, the user
 * adds the Title, Location, Type, and Description as necessary, then chooses a contact, customer, and user from the
 * corresponding dropdown menus, then chooses a start date & time and end date & time.
 */
public class AppointmentFormController {
//    private Stage stage;
//    private Parent scene;

/** Theses TextFields includes the Appointment Description, ID, Location, Title, and Type fields */
    @FXML public TextField apptDescriptionField;
    @FXML public TextField apptIDField;
    @FXML public TextField apptLocationField;
    @FXML public TextField apptTitleField;
    @FXML public TextField apptTypeField;
    @FXML public Button cancelButton;
    @FXML public ComboBox<?> contactDropdown;
    @FXML public ComboBox<?> customerDropdown;
    @FXML public DatePicker dateEndSelection;
    @FXML public DatePicker dateStartSelection;
    @FXML public ComboBox<?> endTimeDropdown;
    @FXML public Label errorLabel;
    @FXML public Button saveButton;
    @FXML public ComboBox<?> startTimeDropdown;
    @FXML public Label timeErrorLabel;
    @FXML public ComboBox<?> userDropdown;

    @FXML void clickCancelButton(ActionEvent event) {

    }

    @FXML void clickSaveButton(ActionEvent event) {

    }

}
